#! /bin/sh

### BEGIN INIT INFO
# Provides:          ntpdate
# Required-Start:    
# Required-Stop:
# Should-Start:      $all
# Default-Start: 2 3 4 5    
# Default-Stop: 0 1 6
# Short-Description: network time sync
# Description: sync date time from internet server.
### END INIT INFO

N=/etc/init.d/ntpdate

set -e

case "$1" in
  start)
        /etc/ntpdate-cubian&
	;;
  stop|reload|restart|force-reload|status)
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
