#! /bin/sh

### BEGIN INIT INFO
# Provides:          networklightctrl
# Required-Start:
# Required-Stop:
# Should-Start: $all
# Default-Start: 2 3 4 5 
# Default-Stop:
# Short-Description: Let blue led on cubieboard indicate network status
# Description: Blink the blue led when network is down.
#	Turn off the blue led when network is available.
### END INIT INFO

N=/etc/init.d/networklightctrl

set -e

case "$1" in
  start|netstatchange)
	# start blink blue led network not connected
        # or turn off led when network is connected
        /etc/networklight&
        ;;
  stop|reload|restart|force-reload|status)
        ;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
